name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0
          components: rustfmt, clippy
      - name: Cargo fmt
        run: cargo fmt --all --check
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Start MLTP Stack
        uses: ./.github/actions/start-mltp-stack
      - name: Cargo test
        run: cargo test --all-features
      - name: Stop MLTP Stack
        if: always()
        uses: ./.github/actions/stop-mltp-stack
